// 第 1 章界面文字（按钮、图例、画布标注），与讲解内容分开
import { COMMON_UI } from '../../common/ui'
import type { PinLabels } from '../../../engine/render/pin/common'
import type { BiText } from '../../../app/settings'

/** PiN 舞台画布上的文字 */
export const PIN_LABELS: Record<keyof PinLabels, BiText> = {
  // 应用
  appDrive: { zh: '工业变频器', en: 'Industrial drive' },
  appDriveSub: { zh: '380 V 电网 → 直流母线约 540 V\n选 1200 V 器件，几十到几百安', en: '380 V mains → ~540 V DC link\n1200 V parts, tens to hundreds of A' },
  appEv: { zh: '800 V 电动汽车', en: '800 V electric vehicle' },
  appEvSub: { zh: '电池电压 800 V 级\n选 1200 V 器件，几百安', en: '800 V-class battery\n1200 V parts, hundreds of A' },
  appPv: { zh: '光伏逆变器', en: 'Solar inverter' },
  appPvSub: { zh: '直流 1000–1500 V，多用三电平拓扑\n每只器件只承受一部分，选 1200 V 级', en: '1000–1500 V DC, often three-level\nEach part sees a share: 1200 V class' },
  mapU: { zh: '耐压（对数坐标）', en: 'Blocking voltage (log)' },
  mapI: { zh: '额定电流（对数坐标）', en: 'Rated current (log)' },
  everyday: { zh: '普通电子器件', en: 'Everyday electronics' },
  power: { zh: '电力电子器件', en: 'Power electronics' },
  ladder: { zh: '常见电压', en: 'Everyday voltages' },
  mapGap: { zh: '耐压高 1–2 个数量级，电流高 2–4 个数量级', en: '1–2 decades more voltage, 2–4 decades more current' },
  mapKey: { zh: '难在"既要高电压，又要大电流"：\n1N4007 能耐 1000 V，却只能过 1 A', en: 'The hard part is high voltage AND high current:\na 1N4007 blocks 1000 V but carries only 1 A' },
  pn0: { zh: '第 0 章示例 PN 结', en: 'Chapter-0 junction' },
  vBat: { zh: '锂电池', en: 'Li-ion cell' },
  vCar: { zh: '汽车蓄电池', en: 'Car battery' },
  vGrid: { zh: '市电峰值（220 V）', en: 'Mains peak (220 V)' },
  vBus: { zh: '变频器母线', en: 'Drive DC link' },
  vEv: { zh: '电动车平台', en: 'EV platform' },
}

export const UI = {
  ...COMMON_UI,
  trace: { zh: '追踪一个空穴', en: 'Trace one hole' },
  urev: { zh: '反向电压', en: 'Reverse voltage' },
  current: { zh: '正向电流', en: 'Forward current' },
  regions: {
    pPlus: { zh: 'P⁺', en: 'P⁺' },
    nMinus: { zh: 'N⁻', en: 'N⁻' },
    n: { zh: 'N', en: 'N' },
    nPlus: { zh: 'N⁺', en: 'N⁺' },
    depl: { zh: '耗尽层', en: 'Depletion layer' },
  },
  chart: {
    fieldAxis: { zh: 'N⁻ 区电场 E（横轴与上面的器件对齐）', en: 'Field E in N⁻ (aligned with the device above)' },
    critical: { zh: '临界场强', en: 'Critical field' },
    areaIsU: { zh: '面积', en: 'Area' },
    concAxis: { zh: 'N⁻ 区载流子浓度（cm⁻³，对数；横轴与上面的器件对齐）', en: 'Carriers in N⁻ (cm⁻³, log; aligned with the device above)' },
    keys: { zh: '曲线：模型稳态 p　圆点：舞台粒子统计', en: 'Curve: model p   Dots: stage particles' },
    ohmic: { zh: '没有空穴注入：导电的只有 N_D 个电子', en: 'No hole injection: only the N_D electrons conduct' },
  },
  dilemma: {
    test: { zh: '两种考验', en: 'Two tests' },
    block: {
      tag: { zh: '考验 ①', en: 'Test ①' },
      title: { zh: '加反向电压', en: 'Reverse voltage' },
      sub: { zh: '比耐压：谁能扛住高电压？', en: 'Who survives high voltage?' },
      next: { zh: '还有第二个考验：加反向电压，比耐压 →', en: 'One more test: reverse voltage →' },
    },
    conduct: {
      tag: { zh: '考验 ②', en: 'Test ②' },
      title: { zh: '通大电流', en: 'Large current' },
      sub: { zh: '比压降：谁让大电流通得"省"？', en: 'Who passes current cheaply?' },
      next: { zh: '别漏了第二个考验：通大电流，比压降 →', en: "Don't miss test ②: large current →" },
    },
    new: { zh: '还没看', en: 'NEW' },
    sameU: { zh: '两个结加同一个反向电压', en: 'Same reverse voltage on both' },
    sameJ: { zh: '两个结通过同样的电流密度（只算欧姆电阻）', en: 'Same current density through both (ohmic only)' },
    dense: { zh: '浓而短', en: 'Heavy and short' },
    light: { zh: '淡而长', en: 'Light and long' },
    spec: { zh: 'N 区 {n} cm⁻³，长 {w} µm', en: 'N region {n} cm⁻³, {w} µm long' },
    speed: { zh: '电子平均速度 v = J/(qn)', en: 'Mean electron speed v = J/(qn)' },
    drop: { zh: '压降', en: 'Drop' },
    heat: { zh: '发热', en: 'Heat' },
    broke: { zh: '击穿！', en: 'Breakdown!' },
    bvName: { zh: '耐压（击穿电压）', en: 'Blocking voltage (breakdown)' },
    dropName: { zh: '100 A/cm² 时 N 区的压降（只算欧姆电阻）', en: 'N-region drop at 100 A/cm² (ohmic only)' },
    heatName: { zh: '通过 30 A 时器件自己发的热（功率 = 压降 × 电流）', en: 'Heat the device itself produces at 30 A (power = drop × current)' },
    blockVerdict: { zh: '淡而长的耐压高约 {k} 倍：⊕ 稀，电场爬得慢，耗尽层能摊得很开', en: 'Light and long blocks ~{k}× more: sparse ⊕, the field rises slowly and spreads far' },
    conductVerdict: { zh: '淡而长的：电子少 {n} 倍、要跑快 {n} 倍，路又长 {l} 倍，压降大约 {k} 倍', en: 'Light and long: {n}× fewer electrons running {n}× faster over a {l}× longer path, ~{k}× the drop' },
    whyLowTitle: { zh: '为什么压降越小越好？', en: 'Why must the drop be small?' },
    whyLow: {
      zh: '器件上掉下的电压 × 流过的电流 = 器件自己发出的热（导通损耗）。通过 30 A 时：浓而短 {ud} V × 30 A ≈ {a} W，淡而长 {ul} V × 30 A ≈ {b} W，相当于一个电热水壶的功率，全挤在指甲盖大的芯片里，散不掉就会烧毁；这些电能也白白变成了热，效率很低。所以大电流下压降必须很小。',
      en: 'Drop × current = heat the device makes itself (conduction loss). At 30 A: heavy and short {ud} V × 30 A ≈ {a} W; light and long {ul} V × 30 A ≈ {b} W — an electric kettle packed into a fingernail-sized chip. It cannot shed that heat and burns out, and all that energy is wasted. So the drop must be small at high current.',
    },
    dilemma: { zh: '耐压要"淡而长"，大电流要"浓而短"：同一个旋钮，两头的要求正好相反，普通 PN 结做不到两全', en: 'Blocking wants light and long, current wants heavy and short: one knob, opposite demands' },
  },
  result: {
    block: { zh: '截止（反偏）：N⁻ 是"耐压层"', en: 'Blocking (reverse): N⁻ is the "voltage layer"' },
    conduct: { zh: '导通（正偏）：N⁻ 是"导电层"', en: 'Conducting (forward): N⁻ is the "current layer"' },
    blockLine: { zh: 'N⁻ 又淡又厚，裸露的 ⊕ 摊在约 {w} µm 里，电场三角形的面积 = {u} V；极限约 {bv} V', en: 'Light and thick: exposed ⊕ spread over ~{w} µm, triangle area = {u} V; limit ~{bv} V' },
    conductLine: { zh: '{i} A 时 N⁻ 被电子和空穴淹没，N⁻ 区只降 {um} V，端电压 {u} V', en: 'At {i} A N⁻ is flooded with electrons and holes: N⁻ drop {um} V, terminal {u} V' },
    boardTitle: { zh: '成绩单：回到 1.1-2 的两个指标（额定 30 A）', en: 'Scoreboard: the two criteria of 1.1-2 (rated 30 A)' },
    bvName: { zh: '耐压（越高越好）', en: 'Blocking voltage (higher is better)' },
    uName: { zh: '导通时的端电压（越低越好）', en: 'On-state terminal voltage (lower is better)' },
    heatName: { zh: '导通时器件自己发的热（越少越好）', en: 'On-state heat in the device (lower is better)' },
    dense: { zh: '浓而短的 PN 结', en: 'Heavy and short PN' },
    light: { zh: '淡而长的 PN 结', en: 'Light and long PN' },
    pin: { zh: 'PiN（P⁺N⁻N⁺）', en: 'PiN (P⁺N⁻N⁺)' },
    boardNote: { zh: '浓而短的 PN 结导通时端电压只有约 {ud} V（结压降按 0.7 V 粗估），可它只能耐约 {bd} V；淡而长的耐压高，端电压却高达 {ul} V。只有 PiN 两项都过关。', en: 'Heavy and short drops only ~{ud} V on state (junction drop roughly 0.7 V), but blocks just ~{bd} V; light and long blocks high but drops {ul} V. Only PiN passes both.' },
    insight: { zh: '同一层 N⁻，截止时是耐压层（又淡又厚，扛住高压），导通时是导电层（被载流子淹没，电阻骤降）：耐压和大电流，PiN 两头都顾上了。', en: 'One N⁻ layer, two roles: a voltage layer when blocking (light and thick), a current layer when conducting (flooded with carriers). PiN gets both.' },
    cost: { zh: '代价：导通时 N⁻ 里存了大量载流子（约 20 µC/cm²），关断时要先清掉——这就是 1.4 的反向恢复。', en: 'The price: ~20 µC/cm² of carriers are stored in N⁻ while on and must be cleared at turn-off, which is the reverse recovery of 1.4.' },
    rated: { zh: '成绩单按额定电流', en: 'Scoreboard at the rated current' },
  },
  structure: {
    heavy: { zh: '重掺杂（＋）', en: 'Heavily doped (＋)' },
    holeSea: { zh: '空穴多得像一片海', en: 'a sea of holes' },
    electronSea: { zh: '电子多得像一片海', en: 'a sea of electrons' },
    light: { zh: '轻掺杂（－）：中间这层最关键', en: 'Lightly doped (－): the key layer' },
    lightWhy: { zh: '比两边稀约 10 万倍（舞台压缩成约 150 倍），电子稀稀拉拉，一个 ⊕ 只配一个电子：专门用来承受电压', en: '~10⁵× sparser than the sides (compressed to ~150× here): few electrons, one per ⊕. It exists to hold the voltage' },
    note: { zh: '"＋"表示重掺杂（浓，载流子多），"－"表示轻掺杂（淡，载流子少）。原来的 PN 结只有 P、N 两层，现在在中间插进一层又淡又厚的 N⁻，两头的 P、N 都改成重掺杂', en: '"＋" = heavy doping (many carriers), "－" = light doping (few). Instead of a plain P–N pair, a light, thick N⁻ layer sits in between, and both outer layers are heavily doped' },
  },
  densityHint: {
    zh: '与第 0 章共用一个设置，只影响画面。默认 200 时 P⁺ 区画 360 个空穴、N⁻ 区 12 个电子；各区按同一比例增减（0.25–2 倍），浓度之比不变',
    en: 'Shared with chapter 0; visual only. At the default 200, P⁺ shows 360 holes and N⁻ 12 electrons; all regions scale together (0.25–2×)',
  },
  hypo: {
    title: { zh: '假想：P⁺ 不注入空穴。', en: 'Hypothetical: P⁺ injects no holes.' },
    body: { zh: '只有 N⁻ 自己的电子在导电（和肖特基、MOSFET 这类单极型器件一样）。每个电子要以 {v} cm/s 的速度跑，已是饱和速度的 {p} %，再快不了，电流上限约 {i} A。', en: 'Only the N⁻ electrons carry current (like Schottky or MOSFET unipolar devices). Each must run at {v} cm/s, {p} % of the saturation speed, which it cannot exceed: the current tops out near {i} A.' },
  },
  ratio: { zh: '示意：舞台上阳极端的等离子体约为 P⁺ 的 {s} %，真实约为 {r} %（舞台压缩了 P⁺ 与 N⁻ 的浓度比，被放大了约 {k} 倍）', en: 'Illustrative: the plasma at the anode end is drawn at ~{s} % of P⁺; in reality ~{r} % (the P⁺/N⁻ density ratio is compressed, exaggerating this ~{k}×)' },
  drop: {
    title: { zh: 'N⁻ 区压降随电流的变化', en: 'N⁻ drop versus current' },
    xAxis: { zh: '正向电流 I / A', en: 'Forward current I / A' },
    yAxis: { zh: 'N⁻ 区压降 / V', en: 'N⁻ drop / V' },
    none: { zh: '没有空穴注入', en: 'No hole injection' },
    with: { zh: '有空穴注入', en: 'With injection' },
    noneWhy: { zh: '只靠 N⁻ 自己的电子，压降与电流成正比，约 62 A 就到头了', en: 'N⁻ electrons only: drop ∝ current, and it stops near 62 A' },
    withWhy: { zh: '电流越大，注入的载流子越多、电阻越小，压降几乎不变', en: 'More current injects more carriers, so the resistance falls and the drop barely moves' },
    sat: { zh: '电子到饱和速度，电流上限', en: 'Electrons at saturation speed: limit' },
    flat: { zh: '几乎不变', en: 'barely changes' },
    beyond: { zh: '已超过电流上限', en: 'beyond the limit' },
  },
  weight: { zh: '等离子体太浓，N⁻ 区按比例画稀：每个粒子代表约 {k} 个（电流越大，粒子越多）', en: 'The plasma is drawn thinned: each particle in N⁻ stands for ~{k} (more current, more particles)' },
  weightHint: { zh: '不管电流多大，每个粒子代表的个数都不变，所以拖动电流时能看到粒子数和计数器的变化', en: 'The scale does not change with current, so dragging the slider visibly changes the particle count and the counters' },
  flow: { zh: '电流（粒子流）', en: 'Current (carrier flow)' },
  flowHint: { zh: '舞台上 A 端每秒流过的粒子数（约 1 s 平滑，示意）。真实电流以 V-A 曲线为准', en: 'Particles per second through the anode on stage (≈1 s average, illustrative). Real current: see the V-A curve' },
  ro: {
    w: { zh: '耗尽层', en: 'Depletion' },
    emax: { zh: '峰值场强', en: 'Peak field' },
    bv: { zh: '击穿电压', en: 'Breakdown' },
    uf: { zh: '端电压 U_F', en: 'Terminal U_F' },
    uj: { zh: '两个结', en: 'Two junctions' },
    um: { zh: 'N⁻ 区', en: 'N⁻ region' },
    ohm: { zh: 'N⁻ 区（欧姆）', en: 'N⁻ region (ohmic)' },
    vel: { zh: '电子平均速度 v = J/(qN_D)', en: 'Mean electron speed v = J/(qN_D)' },
    satFrac: { zh: '已是饱和速度的', en: 'already' },
    j: { zh: '电流密度', en: 'Current density' },
  },
  scaled: {
    apps: { zh: '数值取自各厂家数据手册（见讲解区）；第 0 章示例 PN 结为计算值。', en: 'Ratings from manufacturer datasheets; the chapter-0 junction is computed.' },
    symbol: { zh: '符号按 GB/T 4728.5 / IEC 60617。结构条用 1.1 舞台的比例（P⁺ : N⁻ : N⁺ 不是真实厚度，真实比例见下一步）；第 0 章 PN 结的数值取自第 0 章。', en: 'Symbol per GB/T 4728.5 / IEC 60617. The structure bar uses the 1.1 stage proportions (not real thicknesses; true scale is in the next step); the chapter-0 numbers come from chapter 0.' },
    section: { zh: '正面金属、N⁻ 的厚度取自芯片手册与文献的典型值（1200 V 级 N⁻ 约 85–100 µm，薄片工艺整片约 120 µm，厚衬底工艺 N⁺ 衬底 220–300 µm）；P 阳极、场截止层、N⁺ 阴极、背面金属的厚度各厂差别很大，这里只取量级。电场形状（三角形 / 梯形）与芯片边缘的终端结构图都是示意，不是计算结果。图是竖放的（正面在上，与 3D 模型一致），1.1 的舞台是横放的。', en: 'Front-metal and N⁻ thicknesses are typical values from chip datasheets and papers (N⁻ of 1200 V parts about 85–100 µm, whole chip about 120 µm in thin-wafer processes, 220–300 µm of N⁺ substrate in thick-substrate ones); the P anode, field stop, N⁺ cathode and back metal differ a lot between makers, so only orders of magnitude are drawn. The field shapes (triangle / trapezoid) and the edge-termination drawings are sketches, not calculations. The section is drawn upright (front on top, like the 3D models); the 1.1 stage lies on its side.' },
    to247: { zh: '3D 示意：外形尺寸参照 TO-247（宽约 15.9 mm、塑封厚约 5 mm）；芯片各层厚度放大约 5 倍（真实硅片只有 0.1–0.3 mm），焊料层、键合线、引脚也略作放大；引脚 A、K 的排列是示意，具体型号以数据手册为准；塑封体里面本来看不见，爆炸图是为了讲清结构。', en: '3D illustration: outline follows TO-247 (about 15.9 mm wide, 5 mm thick body); chip layers are ~5× thicker than real (silicon is 0.1–0.3 mm), and solder, wires and leads are slightly enlarged; the A/K pin order is illustrative (see the datasheet of a real part); the inside is normally hidden, and the exploded view is for explanation.' },
    pressfit: { zh: '3D 示意：外形参照常见的陶瓷管壳平板压接型，取外径约 76 mm、高约 26 mm（实际随电流等级变化）；晶圆各层厚度放大了数倍（真实约零点几到一毫米），边缘斜角真实只有几度，这里夸大成约 30°；钼片、铜电极的厚度和法兰的形状为示意；压力箭头只表示方向，大小以数据手册为准；管壳里面本来看不见，爆炸图是为了讲清结构。', en: '3D illustration: outline follows a common ceramic-housing press-pack, drawn about 76 mm across and 26 mm high (the real size varies with the rating); wafer layers are several times thicker than real (a few tenths of a millimetre to about 1 mm), and the bevel, really a few degrees, is drawn at about 30°; the thickness of the moly discs and poles and the flange shape are illustrative; force arrows show direction only, with magnitudes in the datasheet; the inside is normally hidden, and the exploded view is for explanation.' },
    packages: { zh: '简图是示意（不按比例）；电流范围只表示数量级，不是某个型号的额定值；各型号的数据取自厂家数据手册（见讲解区）。实物照片取自 Wikimedia Commons，作者与许可标在每张照片下。', en: 'Drawings are schematic and not to scale; the current ranges are orders of magnitude, not the rating of any part; per-part figures come from manufacturer datasheets (see the text). Photos are from Wikimedia Commons, with author and license under each.' },
    ohmic: { zh: '假想的单极情形（P⁺ 不注入空穴）：电子的速度、箭头长度是示意，不同掺杂之间的速度比为真实值；压降按低场迁移率，接近电流上限时实际更大；N⁻ 里的电子与 ⊕ 个数仍是压缩后的。', en: 'Hypothetical unipolar case (P⁺ injects no holes). Speeds and arrow lengths are illustrative; the drop uses low-field mobility and is larger near the limit; electron and ⊕ counts in N⁻ are compressed.' },
    dilemma: { zh: '与第 0 章同一套粒子。单边突变结（P 区很浓）、平行平面，Baliga 经验式；N 区长度取刚好容纳击穿时的耗尽层。两个结用同一把尺（每微米的像素相同），N 区的电子与 ⊕ 个数 ∝ 掺杂 × 长度（真实比例），P⁺ 区未按比例。扫走电子的速度、雪崩时的产生速率是示意，升压过程放慢；通电流时只算欧姆电阻，两者的电子速度之比为真实值，绝对速度是示意。淡的一侧 3.4 kV/cm 时已有一定的速度饱和，实际压降还要更大。', en: 'Same particles as chapter 0. One-sided abrupt junctions, Baliga fits, N length just holding the breakdown depletion. Same length scale for both; electrons and ⊕ ∝ doping × length. Sweep, avalanche and absolute drift speeds are illustrative; the speed ratio is true.' },
    structure: { zh: '与第 0 章同一套粒子。示意：各区宽度未按比例；浓度压缩——P⁺、N⁺ 的多子约为 N⁻ 的 150 倍（真实约 10⁵ 倍）；N⁻ 区一个 ⊕ 配一个电子。', en: 'Same particles as chapter 0. Widths not to scale; densities compressed: P⁺ and N⁺ hold ~150× the N⁻ carriers (really ~10⁵×); one electron per ⊕ in N⁻.' },
    reverse: { zh: '耗尽层近似；P⁺ 一侧裸露的受主与 N⁻ 一侧的施主一样多，只是挤在很薄一层里。扫走载流子的速度与耗尽层里的热产生速率都是示意（放大）；终端结构另计（1.2）。', en: 'Depletion approximation; the P⁺ side exposes as many acceptors as N⁻ exposes donors, in a very thin layer. Sweep speed and generation rate are illustrative.' },
    result: { zh: '上、下两个舞台是同一个 PiN（同一套粒子），分别在反偏和正偏。舞台把 P⁺ 与 N⁻ 的浓度比压缩成约 150 倍，等离子体与 P⁺ 的浓度比因此被放大了几十倍（图例里写明）；扫走载流子的速度、热产生速率是示意。成绩单为模型计算值（25 °C、额定 30 A；击穿用 Baliga 经验式，不含终端结构；普通 PN 结的结压降粗估 0.7 V，没计速度饱和，淡而长的实际压降更大）。', en: 'Both stages are the same PiN (same particles), one reverse and one forward. The P⁺/N⁻ density ratio is compressed to ~150×, which exaggerates the plasma/P⁺ ratio (see legend); sweep speed and thermal generation are illustrative. Scoreboard values come from the model (25 °C, rated 30 A; Baliga breakdown, no termination; plain-junction drop roughly 0.7 V, no velocity saturation, so light-and-long is worse in reality).' },
    forward: { zh: '粒子与第 0 章同样做热运动、漂移、扩散、复合；N⁻ 区电场取模型的双极电场，扩散长度与 N⁻ 厚度之比取真实值，舞台寿命 7 s（真实 0.2 µs）。舞台把等离子体与 P⁺ 的浓度比放大了几十倍（图例里写明）。', en: 'Particles drift, diffuse and recombine as in chapter 0, driven by the model ambipolar field in N⁻; real L_a/W; stage lifetime 7 s (real 0.2 µs). The plasma-to-P⁺ density ratio is exaggerated (see legend).' },
  },
  va: {
    title: { zh: 'V-A 曲线', en: 'V-A curve' },
    rev: { zh: '反向（阻断）', en: 'Reverse (blocking)' },
    fwd: { zh: '正向（导通）', en: 'Forward (conduction)' },
    ohmic: { zh: '没有电导调制（只算欧姆电阻）', en: 'No modulation (ohmic only)' },
    pin: { zh: '示例 PiN（有电导调制）', en: 'Example PiN (modulated)' },
    bv: { zh: '击穿', en: 'Breakdown' },
    zoom: { zh: '横轴 0–2 V', en: 'Axis 0–2 V' },
    wide: { zh: '横轴 0–45 V', en: 'Axis 0–45 V' },
    leak: { zh: '漏电流很小，按 µA 画', en: 'Leakage is tiny: drawn in µA' },
    scales: { zh: '正向（V、A）与反向（kV、µA）比例不同', en: 'Forward (V, A) and reverse (kV, µA) use different scales' },
  },
}
