// 界面文字（按钮、图例、标注等），与讲解内容分开。讲解正文暂只有中文，界面文字保留中英
import { COMMON_UI } from '../../common/ui'
import { BD } from './uiBreakdown'

export const UI = {
  ...COMMON_UI,
  view: { zh: '显示方式', en: 'View' },
  views: {
    particles: { zh: '粒子', en: 'Particles' },
    flow: { zh: '箭头+浓度', en: 'Flow & density' },
    both: { zh: '叠加', en: 'Overlay' },
  },
  layers: { zh: '图层', en: 'Layers' },
  layerNames: {
    field: { zh: '电场 |E|', en: 'Field |E|' },
    potential: { zh: '电势 φ', en: 'Potential φ' },
    conc: { zh: '浓度 n、p', en: 'Density n, p' },
    band: { zh: '能带', en: 'Band diagram' },
  },
  rowNotes: {
    field: { zh: '方向：N → P', en: 'Points N → P' },
    potential: { zh: '以 A 端为零点', en: 'Relative to terminal A' },
    conc: { zh: '对数坐标，来自粒子统计', en: 'Log scale, counted from particles' },
    band: { zh: '实线 E_c、E_v，虚线为准费米能级', en: 'Solid: E_c, E_v. Dashed: quasi-Fermi levels' },
  },
  regions: {
    p: { zh: 'P 区（受主掺杂）', en: 'P region (acceptors)' },
    n: { zh: 'N 区（施主掺杂）', en: 'N region (donors)' },
    scr: { zh: '空间电荷区', en: 'Space-charge region' },
    scrHigh: { zh: '结区', en: 'Junction region' },
  },
  /** 窄屏用的短标签 */
  regionsShort: {
    p: { zh: 'P 区', en: 'P' },
    n: { zh: 'N 区', en: 'N' },
    scr: { zh: '耗尽层', en: 'SCR' },
    scrHigh: { zh: '结区', en: 'Junction' },
  },
  highInjection: {
    zh: '注入的载流子已接近掺杂浓度，结区不再耗尽',
    en: 'Injected carriers approach the doping level; the junction is no longer depleted',
  },
  potentialSplit: { zh: '紫：结上的台阶 {j} V　灰：体电阻压降 {r} V', en: 'Purple: junction step {j} V. Grey: bulk drop {r} V' },
  tube: {
    stage: { zh: '舞台', en: 'Stage' },
    caption: {
      zh: '截面里有成千上万根细柱（这里只画 6×6 根），舞台画的是黄色的那一根',
      en: 'The cross-section holds countless thin columns (6×6 drawn here); the stage shows the yellow one',
    },
    close: { zh: '收起小图', en: 'Hide inset' },
  },
  lanes: {
    e: { zh: '电子浓度', en: 'Electrons' },
    h: { zh: '空穴浓度', en: 'Holes' },
  },
  bias: { zh: '外加电压', en: 'Applied voltage' },
  biasFixed: { zh: '本节固定，不可调', en: 'Fixed for this step' },
  diffusion: { zh: '扩散', en: 'Diffusion' },
  drift: { zh: '漂移', en: 'Drift' },
  scaled: {
    zh: '示意：时间放慢，少子寿命在舞台上约 2–3 s；扩散长度压缩到与耗尽层同量级（真实约为 500 倍）；势垒按 6 个 kT 显示（真实约 31 个 kT）；导线珠子只表示电子流动的方向与多少，不代表真实速度；空穴画成大一圈的空心圆环只为区分，不代表真实尺寸。下方曲线使用真实电压。',
    en: 'Illustrative: time is slowed so a minority carrier lives about 2–3 s on stage; the diffusion length is squeezed to the depletion width (really ~500× longer); the barrier is drawn as 6 kT (really ~31 kT); wire beads show only direction and amount, not real speed; holes are drawn as larger hollow rings only to tell them apart. Curves below use real voltages.',
  },
  current: { zh: '净电流（约 5 s 平均）', en: 'Net current (≈5 s average)' },
  currentHint: {
    zh: '舞台上越过结的载流子数（每秒），折算到固定规模，与屏幕上画多少粒子无关。真实电流以 V-A 曲线为准',
    en: 'Carriers crossing per second on stage, scaled to a fixed size and independent of how many are drawn. Real current: see the V-A curve',
  },
  density: { zh: '粒子数', en: 'Particles' },
  densityHint: {
    zh: '每种载流子在屏幕上画多少个。只影响画面，不影响电流计和曲线',
    en: 'How many of each carrier are drawn. Visual only; meters and curves do not change',
  },
  temp: { zh: '温度', en: 'Temperature' },
  counters: {
    inK: { zh: 'K 端流入', en: 'In at K' },
    outA: { zh: 'A 端流出', en: 'Out at A' },
    inA: { zh: 'A 端流入', en: 'In at A' },
    outK: { zh: 'K 端流出', en: 'Out at K' },
    hint: { zh: '导线中经过的电子数，换步或正偏、反偏切换时清零', en: 'Electrons through the wire; reset on a new step or when the bias changes polarity' },
  },
  legend: {
    electron: { zh: '自由电子', en: 'Electron' },
    hole: { zh: '空穴', en: 'Hole' },
    heatOut: { zh: '一次复合：放热', en: 'Recombination: heat released' },
    heatIn: { zh: '一次产生：吸热', en: 'Generation: heat absorbed' },
    bead: { zh: '导线中的电子', en: 'Electrons in the wire' },
    groupCenter: { zh: '电子群的重心（带短轨迹）', en: 'Centre of the marked group (with a short trail)' },
    groupSpread: { zh: '电子群的分布范围（1σ）', en: 'Spread of the group (1σ)' },
    drift: { zh: '该区平均定向速度（示意放大）', en: 'Mean directed velocity in that region (magnified)' },
    driftFew: { zh: '该区这种载流子太少，平均值没有意义', en: 'Too few of this carrier there for a meaningful average' },
  },
  group: {
    mark: { zh: '标记一群电子', en: 'Mark a group of electrons' },
    clear: { zh: '取消标记', en: 'Clear the mark' },
    few: { zh: '只剩 {n} 个了，点此重新标记', en: 'Only {n} left. Mark a new group' },
  },
  driftToggle: { zh: '平均定向速度', en: 'Mean directed velocity' },
  trace: {
    start: { zh: '追踪一个载流子', en: 'Follow one carrier' },
    stop: { zh: '结束追踪', en: 'Stop following' },
    next: { zh: '换一个', en: 'Pick another' },
    title: { zh: '它的一生', en: 'Its life' },
    kind: { 0: { zh: '电子', en: 'Electron' }, 1: { zh: '空穴', en: 'Hole' } },
    origin: { zh: '来历', en: 'Origin' },
    origins: {
      // 按载流子种类：[电子, 空穴]
      wireK: [
        { zh: '从 K 端导线流入', en: 'Entered from the wire at K' },
        { zh: '在 K 端产生：导线抽走一个价电子', en: 'Born at K: the wire pulled out a valence electron' },
      ],
      wireA: [
        { zh: '从 A 端导线流入', en: 'Entered from the wire at A' },
        { zh: '在 A 端产生：导线抽走一个价电子', en: 'Born at A: the wire pulled out a valence electron' },
      ],
      gen: { zh: '热产生：电子和空穴成对出现（吸热）', en: 'Thermal generation: born as an electron-hole pair (heat absorbed)' },
      initial: { zh: '开始追踪前已在器件中', en: 'Already in the device when tracking began' },
    },
    now: { zh: '现在', en: 'Now' },
    regions: {
      P: { zh: 'P 区', en: 'P region' },
      N: { zh: 'N 区', en: 'N region' },
      SCR: { zh: '耗尽层', en: 'depletion region' },
    },
    minority: { zh: '少子', en: 'minority' },
    majority: { zh: '多子', en: 'majority' },
    crossings: { zh: '追踪中越过结', en: 'Crossings while followed' },
    times: { zh: '次', en: '×' },
    age: { zh: '存活', en: 'Alive for' },
    ageNote: { zh: '（舞台时间，从开始追踪算起）', en: '(stage time, since tracking began)' },
    ageNoteBirth: { zh: '（舞台时间，从出生算起）', en: '(stage time, since birth)' },
    status: {
      free: { zh: '自由运动中', en: 'Moving freely' },
      recombined: { zh: '与一个异性载流子成对消失（复合），能量变成热', en: 'Vanished together with a carrier of the opposite kind (recombined); the energy became heat' },
      exitedE: { zh: '离开器件，流入导线', en: 'Left the device into the wire' },
      exitedH: { zh: '到达电极，被导线送来的电子填掉', en: 'Reached the contact and was filled by an electron from the wire' },
    },
    next4s: { zh: '几秒后自动换下一个', en: 'Switching to another in a few seconds' },
  },
  /** "一个电子走一圈"示意演示与旁边的说明 */
  lap: {
    start: { zh: '演示：一个电子走一圈', en: 'Demo: one electron goes round' },
    stop: { zh: '结束演示', en: 'Stop the demo' },
    again: { zh: '再演示一次', en: 'Play again' },
    close: { zh: '关闭说明', en: 'Close' },
    needFwd: { zh: '加上正向电压（0.3 V 以上）后才能演示', en: 'Apply a forward voltage (above 0.3 V) first' },
    tag: { zh: '示意演示，不是仿真结果', en: 'Illustration, not simulation' },
    fast: { zh: '快进', en: 'fast-forward' },
    legs: [
      { zh: 'N 区的自由电子（多子），在 N 区里乱跑', en: 'A free electron (majority carrier) wandering in N' },
      { zh: '翻过变矮的坡，进入 P 区，成了少子', en: 'Climbs the lowered barrier into P and becomes a minority carrier' },
      { zh: '在 P 区里扩散，继续乱跑', en: 'Diffuses on through P' },
      { zh: '与一个空穴复合：落进空座位，成了共价键上的价电子', en: 'Recombines with a hole: drops into the empty seat and becomes a valence electron' },
      { zh: '空穴从它身边经过一次，它就向 A 端挪一个座位', en: 'Each time a hole passes by, it moves one seat towards A' },
      { zh: '到达 A 端，进入导线，经过电源', en: 'Reaches A, enters the wire and passes through the battery' },
      { zh: '从 K 端回到 N 区，又是自由电子，一圈完成', en: 'Re-enters N at K as a free electron: one round complete' },
    ],
    realTitle: { zh: '实际情况和演示不一样（以下只作说明）', en: 'Reality differs from the demo (for explanation only)' },
    real: [
      {
        zh: '电流靠接力：K 端流入一个电子的同时，A 端就流出一个（看两个计数器），并不需要等某个电子走完一圈。',
        en: 'Current is a relay: as one electron enters at K, one leaves at A (see the counters). Nobody waits for a single electron to go round.',
      },
      {
        zh: '真走一圈要很久。示例 PN 结在 10 mA 时，价电子靠空穴挪动的平均速度只有约 0.25 µm/s，P 区每 10 µm 要走约 40 s；0.5 mm² 铜导线里电子的平均漂移速度约 1.5 µm/s，走 0.5 m 要四天左右。演示把这些路段都大大快进了。',
        en: 'A real round trip takes very long. At 10 mA in the example junction, a valence electron creeps along at about 0.25 µm/s on average (about 40 s per 10 µm of P); in a 0.5 mm² copper wire the drift speed is about 1.5 µm/s, so 0.5 m takes about four days. The demo fast-forwards all of this.',
      },
      {
        zh: '路线不止这一条：注入 P 区的电子，有的在途中复合，有的直接扩散到 A 端（P 区比扩散长度短得多时这样的更多），也有的又退回 N 区；N 区的电子也可能先和注入 N 区的空穴复合，再以价电子的身份借空穴挪过结。',
        en: 'There are other routes: of the electrons injected into P, some recombine on the way, some diffuse straight to A (more so when P is much shorter than the diffusion length), some return to N; an electron in N may also recombine with a hole injected into N and then cross the junction as a valence electron.',
      },
      {
        zh: '电子彼此完全相同，分不出"哪一个"；"同一个电子走一圈"只是帮助理解的说法。',
        en: 'Electrons are identical and cannot be told apart; "the same electron going round" is only a way of picturing it.',
      },
      {
        zh: '这条路线是预先编排的，不是舞台仿真算出来的；计数器和电流计里不包含这个电子。',
        en: 'The route is scripted, not computed by the stage simulation; the counters and the meter do not include this electron.',
      },
    ],
  },
  /** 静态 V-A 曲线 */
  vi: {
    title: { zh: '静态 V-A 特性', en: 'Static V-A curve' },
    hint: { zh: '拖动圆点改变电压', en: 'Drag the dot to set the voltage' },
    hintLocked: { zh: '这一步的电压由开关过程决定，曲线只作对照', en: 'The voltage here is set by the switching circuit; the curve is for reference' },
    zoomIn: { zh: '纵轴放大 10 倍', en: 'Zoom the I axis 10×' },
    zoomReset: { zh: '还原纵轴', en: 'Reset the I axis' },
    scale: { zh: '纵轴', en: 'I axis' },
    lin: { zh: '线性', en: 'Linear' },
    log: { zh: '对数 |I|', en: 'Log |I|' },
    axisBreak: { zh: '横轴两侧比例不同', en: 'Axis scales differ' },
    revFlat: { zh: '反向电流只有 pA 级，在线性坐标上贴着横轴', en: 'Reverse current is only pA; it hugs the axis on a linear scale' },
    bv: { zh: '击穿约在 −31 V（图外）', en: 'Breakdown near −31 V (off the chart)' },
    total: { zh: '总电流（扩散 + 耗尽层产生）', en: 'Total (diffusion + depletion-region generation)' },
    ideal: { zh: '理想扩散电流', en: 'Ideal diffusion current' },
    ghost: { zh: '放大前的画面', en: 'Before zooming' },
    ref: { zh: '参考温度', en: 'Reference temperatures' },
    diff: { zh: '扩散', en: 'Diffusion' },
    gen: { zh: '产生', en: 'Generation' },
  },
  /** 交流小信号（0.7） */
  ac: {
    toggle: { zh: '叠加交流小信号', en: 'Add a small AC signal' },
  },
  /** 交流小信号下的充电、放电提示（0.7） */
  cap: {
    charge: { zh: '充电', en: 'Charging' },
    discharge: { zh: '放电', en: 'Discharging' },
    chargeWhy: {
      B: { zh: '反压变大，耗尽层变宽：两侧裸露的离子（极板上的电荷）增多', en: 'More reverse voltage, wider depletion layer: more exposed ions (more charge on the plates)' },
      D: { zh: '正向电压升高：结两侧的少子小山长高，存的电荷增多', en: 'Forward voltage rises: the minority hills grow, storing more charge' },
    },
    dischargeWhy: {
      B: { zh: '反压变小，耗尽层变窄：离子又被载流子盖住，极板上的电荷减少', en: 'Less reverse voltage, narrower depletion layer: ions are covered again, less charge on the plates' },
      D: { zh: '正向电压降低：小山变矮，存的电荷减少', en: 'Forward voltage falls: the hills shrink, storing less charge' },
    },
    hillP: { zh: '电子小山', en: 'Electron hill' },
    hillN: { zh: '空穴小山', en: 'Hole hill' },
  },
  /** 开关控制（0.8） */
  sw: {
    off: { zh: '闭合开关 S（二极管关断）', en: 'Close S (diode turns off)' },
    on: { zh: '断开开关 S（二极管开通）', en: 'Open S (diode turns on)' },
    offAgain: { zh: '再来一次：闭合 S', en: 'Again: close S' },
    onAgain: { zh: '再来一次：断开 S', en: 'Again: open S' },
    prep: { zh: '准备中…', en: 'Preparing…' },
    still: {
      intro: { zh: '这一步不换流：二极管稳态正向导通。对照看下方的静态伏安曲线和动态开关曲线（预览）。', en: 'No switching in this step: the diode conducts steadily. Compare the static V-A curve with the switching waveforms (preview) below.' },
      compare: { zh: '这一步不换流：拖动滑块改变条件，下方开通、关断两张图同时更新（上一组为虚线）。', en: 'No switching in this step: move the sliders and both the turn-on and turn-off charts update (previous set dashed).' },
    },
    settle: { zh: '准备中：在换流前的稳态停留，让少子分布稳定下来（快进 2 倍）', en: 'Settling into the steady state before switching (2× fast-forward)' },
    ready: { zh: '准备好了：二极管稳态正向导通，按左边的按钮闭合开关 S，开始换流', en: 'Ready: the diode conducts steadily. Press the button to close S and start switching' },
    run: { zh: '换流中（慢放 4 倍）', en: 'Switching (4× slow motion)' },
    paused: { zh: '停在了这一步要看的时刻，按「播放」继续', en: 'Paused at the moment of interest. Press Play to continue' },
    done: { zh: '已到换流后的稳态', en: 'Settled after switching' },
    circuit: { zh: 'U_R = 2 V，RC 缓冲 2 nF', en: 'U_R = 2 V, 2 nF RC snubber' },
    vD: { zh: '二极管电压', en: 'Diode voltage' },
    IF: { zh: '正向电流 I_F', en: 'Forward current I_F' },
    didt: { zh: '下降速率 di_F/dt', en: 'Fall rate di_F/dt' },
  },
  /** 测试电路（0.8），与波形同步 */
  circ: {
    title: { zh: '测试电路', en: 'Test circuit' },
    hint: { zh: '与波形同步；箭头越粗电流越大', en: 'In step with the waveforms; thicker arrow = more current' },
    load: { zh: '负载（大电感）', en: 'Load (large L)' },
    closed: { zh: 'S 闭合', en: 'S closed' },
    open: { zh: 'S 断开', en: 'S open' },
    ph: {
      offPre: { zh: '开关 S 断开：负载电流 I_F 全部流过二极管，二极管正向导通。', en: 'S open: the whole load current I_F flows through the diode, which conducts.' },
      offFall: { zh: 'S 闭合：U_R 经换流电感 L 把电流推向开关支路，二极管电流按 di_F/dt 下降。', en: 'S closed: U_R, through the commutation inductor L, pushes current into the switch branch; the diode current falls at di_F/dt.' },
      offStore: { zh: '二极管电流过零后继续反向：结两侧存储的少子被抽回，二极管还没有开始阻断，电压仍是正的。', en: 'The diode current passes zero and reverses: stored minority carriers are pulled back; the diode is not blocking yet and its voltage is still positive.' },
      offRecover: { zh: '结边的少子清空，二极管开始承受反压，反向电流迅速回零；电流变化很快，L 感应出电压，二极管上出现反向过冲。', en: 'The junction edges are cleared, the diode starts to block and the reverse current collapses; the fast change makes L induce a voltage, so the diode sees a reverse overshoot.' },
      offBlock: { zh: '恢复阻断：负载电流全部走开关支路，二极管承受反压 −U_R，只剩极小的漏电流。', en: 'Blocking again: the load current all flows in the switch branch; the diode holds −U_R with only a tiny leakage.' },
      onPre: { zh: '开关 S 闭合：负载电流走开关支路，二极管承受反压 −U_R 而截止。', en: 'S closed: the load current flows in the switch branch; the diode is reverse-biased at −U_R and off.' },
      onShift: { zh: 'S 断开中：开关支路的电流按 di_F/dt 下降，负载电流逐渐转入二极管；耗尽层很快变窄，二极管电压升到正向压降附近。', en: 'S opening: the switch-branch current falls at di_F/dt and the load current moves into the diode; the depletion layer narrows quickly and the diode voltage rises to about its forward drop.' },
      onBuild: { zh: '负载电流全部流过二极管：电压早已到位，结两侧的少子小山还在一点点堆高。', en: 'All the load current is in the diode: the voltage settled long ago, but the minority hills are still building up.' },
    },
  },
  /** 动态波形（0.8） */
  scope: {
    title: { zh: '动态特性：电流、电压随时间', en: 'Switching waveforms' },
    titlePreview: { zh: '动态开关曲线（预览：一次关断）', en: 'Switching waveforms (preview: one turn-off)' },
    titleOn: { zh: '开通波形', en: 'Turn-on waveforms' },
    titleOff: { zh: '关断波形', en: 'Turn-off waveforms' },
    hint: { zh: '由扩散方程与外电路联立算出', en: 'Solved from the diffusion equation and the circuit' },
    ghost: { zh: '上一次', en: 'Previous' },
    now: { zh: '本次', en: 'This run' },
    qrr: { zh: '阴影：反向恢复电荷 Q_rr', en: 'Shaded: reverse-recovery charge Q_rr' },
    fit: { zh: '虚线：过 0.9 I_RM 与 0.25 I_RM 两点外推，交零线处为 t₂', en: 'Dashed: line through 0.9 I_RM and 0.25 I_RM; it crosses zero at t₂' },
    charge: { zh: '存储电荷', en: 'Stored charge' },
    t90: { zh: '存储电荷堆到 90%', en: 'Stored charge at 90%' },
    phase: {
      offBefore: { zh: '换流前：稳态正向导通，结两侧存着少子小山，存储电荷 Q_F = τI_F。', en: 'Before switching: steady forward conduction; the minority hills hold Q_F = τI_F.' },
      offFall: { zh: '电流按 di_F/dt 下降。结两侧仍有大量少子，结仍正偏，电压几乎不变。', en: 'The current ramps down at di_F/dt. The hills are still there, so the junction stays forward biased and the voltage barely changes.' },
      offRev: { zh: '电流已经反向：小山里的少子被抽回。结边还有多余少子，结仍正偏，电压仍为正，二极管还没有开始阻断。', en: 'The current has reversed: stored carriers are pulled back. Excess carriers remain at the junction edge, so it is still forward biased and the voltage is still positive.' },
      offBlock: { zh: '结边的多余少子已清空，结开始承受反压、耗尽层展宽；反向电流衰减，换流电感感应出反向电压过冲。', en: 'The junction edge is cleared; the junction takes reverse voltage and the depletion layer widens. The reverse current decays and the inductor drives a voltage overshoot.' },
      offDone: { zh: '恢复阻断：剩下的少子被抽走或复合掉，反向电流逐渐衰减到接近零，电压回到 −U_R。', en: 'Recovered: the remaining carriers are extracted or recombine; the reverse current decays towards zero and the voltage settles at −U_R.' },
      onBefore: { zh: '换流前：反偏截止，耗尽层较宽，几乎没有电流。', en: 'Before switching: reverse biased and blocking; the depletion layer is wide and there is almost no current.' },
      onRise: { zh: '电流转入二极管：先改变势垒电容和缓冲电容上的电压，耗尽层变窄，电压从 −U_R 迅速升高。', en: 'Current moves into the diode. It first changes the voltage on the barrier and snubber capacitances; the depletion layer narrows and the voltage rises quickly from −U_R.' },
      onFill: { zh: '结边的少子浓度很快建立，电压已接近 U_F；离结较远处的小山还在继续堆高，存储电荷要约 2.5τ 才堆到 90%。', en: 'The edge density builds quickly, so the voltage is already near U_F; the hills further out keep growing, and the stored charge takes about 2.5τ to reach 90%.' },
    },
  },
  /** 开关轨迹（0.8） */
  traj: {
    title: { zh: '回到 V-A 平面：关断轨迹', en: 'Turn-off path in the V-A plane' },
    hint: { zh: '线性坐标，单一比例', en: 'Linear axes, one scale' },
    static: { zh: '静态 V-A 曲线', en: 'Static V-A curve' },
    path: { zh: '关断时的工作点轨迹', en: 'Operating point during turn-off' },
    q4: { zh: '第四象限：v > 0，i < 0', en: 'Fourth quadrant: v > 0, i < 0' },
    q3: { zh: '第三象限：反向电流远大于漏电流', en: 'Third quadrant: far above the leakage' },
  },
  /** C-V 曲线（0.7） */
  cv: {
    title: { zh: 'C-V 特性', en: 'C-V curve' },
    hint: { zh: '拖动圆点改变电压', en: 'Drag the dot to set the voltage' },
    cb: { zh: '势垒电容', en: 'Barrier capacitance' },
    cd: { zh: '扩散电容', en: 'Diffusion capacitance' },
    cj: { zh: '结电容', en: 'Junction capacitance' },
    extrap: { zh: '虚线：耗尽层近似失效，按切线外推', en: 'Dashed: depletion approximation fails; tangent extrapolation' },
    noCd: { zh: '正偏时还有扩散电容，这里先不画（见「扩散电容」一步）', en: 'Forward bias adds a diffusion capacitance, not drawn yet (see the next steps)' },
    swing: { zh: '交流信号扫过的范围', en: 'Range swept by the AC signal' },
  },
  /** 晶格舞台（0.1–0.2） */
  lattice: {
    dopant: { zh: '杂质', en: 'Dopant' },
    dopants: {
      P: { zh: '磷（N 型）', en: 'Phosphorus (N-type)' },
      B: { zh: '硼（P 型）', en: 'Boron (P-type)' },
    },
    conc: { zh: '掺杂浓度', en: 'Doping' },
    zeroK: { zh: '（0 K）', en: ' (0 K)' },
    hop: { zh: '跳一步', en: 'One hop' },
    hops: { zh: '已跳 {n} 步', en: '{n} hops so far' },
    hopNote: {
      zh: '为了看清楚，这里每次都让右边的电子跳进来；没有电场时，真实的跳跃方向是随机的',
      en: 'For clarity the electron always comes from the right here; without a field the real hops go in random directions',
    },
    fieldOn: { zh: '加电场', en: 'Apply field' },
    fieldOff: { zh: '撤去电场', en: 'Remove field' },
    current: { zh: '平均电流（加电场以来）', en: 'Mean current (since the field was applied)' },
    exitE: { zh: '电子从左端离开 {n} 个', en: '{n} electrons left at the left' },
    exitH: { zh: '空穴从右端离开 {n} 个', en: '{n} holes left at the right' },
    currentHint: {
      zh: '两种载流子各自贡献的电流（个/秒，舞台时间）。电子向左、空穴向右，电流方向相同，相加',
      en: 'Current carried by each kind (per stage second). Electrons go left, holes go right; both give current in the same direction and add up',
    },
    real: { zh: '真实浓度（cm⁻³）', en: 'Real density (cm⁻³)' },
    shown: { zh: '画面上：{e} 个电子、{h} 个空穴', en: 'On screen: {e} electrons, {h} holes' },
    lens: { zh: '空穴放大镜', en: 'Hole magnifier' },
    lensHint: { zh: '点任一空穴，打开放大镜；再点放大镜关闭', en: 'Click a hole to magnify it; click the lens to close' },
    lensGone: { zh: '一个自由电子落进了这个空位（复合）', en: 'A free electron fell into this vacancy (recombination)' },
    legend: {
      atom: { zh: '硅原子', en: 'Silicon atom' },
      bond: { zh: '共价键上的一对电子', en: 'Electron pair in a covalent bond' },
      vacancy: { zh: '键上的空位（空穴）', en: 'Vacancy in a bond (hole)' },
      P: { zh: '磷原子（施主）', en: 'Phosphorus (donor)' },
      B: { zh: '硼原子（受主）', en: 'Boron (acceptor)' },
      ionP: { zh: '施主离子 ⊕（固定）', en: 'Donor ion ⊕ (fixed)' },
      ionB: { zh: '受主离子 ⊖（固定）', en: 'Acceptor ion ⊖ (fixed)' },
      field: { zh: '电场方向', en: 'Field direction' },
      hopE: { zh: '价电子的一跳（向左）', en: 'One hop of a valence electron (leftward)' },
      hopH: { zh: '空位累计移动（向右）', en: 'Net shift of the vacancy (rightward)' },
    },
    scaled: {
      zh: '示意：晶格画成平面方格；时间大大放慢；画面上的载流子个数做了压缩（本征对数只随 nᵢ 的 1/5 次方变化，掺杂时少子至少画 1 个），真实浓度见计数器。掺杂浓度每升高十倍，画面里的离子与多子只增加一小档——10¹⁴ 与 10¹⁸ cm⁻³ 相差一万倍，粒子数却只多一两倍；数量级的差距请看计数器的数字，不要用画面里粒子的多少来判断。',
      en: 'Illustrative: the lattice is drawn flat; time is greatly slowed; carrier counts on screen are compressed (intrinsic pairs follow nᵢ to the 1/5 power; at least one minority carrier is drawn when doped). Real densities are in the counters. Dopant ion and majority-carrier counts increase only slightly per decade of doping — 10¹⁴ and 10¹⁸ cm⁻³ differ by 10 000×, yet the on-screen counts differ by only about 2×. Use the counter readout, not the particle density, to gauge the true concentration.',
    },
    ni: {
      title: { zh: '载流子浓度与温度', en: 'Carrier density vs temperature' },
      hint: { zh: '对数纵轴；拖动改变温度', en: 'Log scale; drag to set the temperature' },
      ni: { zh: '本征 nᵢ', en: 'Intrinsic nᵢ' },
      maj: { zh: '多子', en: 'Majority' },
      min: { zh: '少子', en: 'Minority' },
      N: { zh: '掺杂浓度', en: 'Doping' },
      tMax: { zh: '硅器件常见最高结温', en: 'Typical max junction temp. of Si devices' },
      offChart: { zh: '低于图表范围', en: 'Below the chart' },
    },
  },
  /** 反向击穿舞台与图表（0.6） */
  bd: BD,
}
