// 0.6 反向击穿舞台与 V-A 图表的界面文字（从 ui.ts 分出，ui.ts 里以 UI.bd 引用）

export const BD = {
  device: { zh: '示例器件', en: 'Example device' },
  vr: { zh: '反向电压', en: 'Reverse voltage' },
  limit: { zh: '限流', en: 'Current limit' },
  limits: {
    on: { zh: '串联限流电阻', en: 'Series resistor' },
    off: { zh: '不限流', en: 'No limit' },
  },
  cooling: { zh: '散热', en: 'Cooling' },
  view: { zh: '画面', en: 'View' },
  views: {
    space: { zh: '座位视角', en: 'Seats' },
    band: { zh: '能带视角', en: 'Band diagram' },
  },
  inject: { zh: '注入', en: 'Inject' },
  injects: {
    one: { zh: '一次一个', en: 'One at a time' },
    stream: { zh: '连续', en: 'Continuous' },
  },
  coolings: {
    good: { zh: '良好（175 °C/W）', en: 'Good (175 °C/W)' },
    poor: { zh: '较差（350 °C/W）', en: 'Poor (350 °C/W)' },
  },
  /** 舞台顶部的读数 */
  ro: {
    W: { zh: '耗尽层', en: 'Depletion' },
    Emax: { zh: '最大电场', en: 'Peak field' },
    M: { zh: '倍增因子', en: 'Multiplication' },
    mCap: { zh: '（画面封顶 {n}）', en: ' (capped at {n} on screen)' },
    vzT: { zh: '此温度下 U_Z', en: 'U_Z at this temperature' },
    mfp: { zh: '平均自由程 ×{k}（相对 25 °C）', en: 'Mean free path ×{k} (vs 25 °C)' },
    tally: { zh: '画面上已注入 {i} 个电子，共流出 {o} 个，平均每个 {m}', en: 'On screen: {i} electrons in, {o} out, {m} each on average' },
    Eg: { zh: '禁带', en: 'Band gap' },
    d: { zh: '隧穿距离', en: 'Tunnelling distance' },
    Tj: { zh: '结温', en: 'Junction temp.' },
    P: { zh: '功耗', en: 'Power' },
    burnt: { zh: '已损坏', en: 'Destroyed' },
  },
  legend: {
    ionA: { zh: '受主离子 ⊖（固定）', en: 'Acceptor ion ⊖ (fixed)' },
    ionD: { zh: '施主离子 ⊕（固定）', en: 'Donor ion ⊕ (fixed)' },
    field: { zh: '电场 𝓔(x)', en: 'Field 𝓔(x)' },
    other: { zh: '另两款在各自 U_Z 时', en: 'The other two at their U_Z' },
    phonon: { zh: '撞上晶格（原子抖一下，声子散射）：能量清零、变成热', en: 'Hits the lattice (the atom shakes; phonon scattering): energy lost as heat' },
    ionize: { zh: '撞翻一个座位：撞出一对电子–空穴', en: 'Knocks an electron out of a seat: a new electron–hole pair' },
    ionZone: { zh: '电场越强底色越深（撞出主要发生在这里）', en: 'Darker = stronger field (most pairs are made here)' },
    seat: { zh: '座位：共价键上的一对价电子', en: 'Seat: a bond with its two valence electrons' },
    bar: { zh: '能量条：攒到的能量，满格才撞得出一对', en: 'Energy bar: energy gained; full = enough to make a pair' },
    gens: { zh: '轨迹颜色：第几代电子', en: 'Trail colour: electron generation' },
    thr: { zh: '撞出线：攒到这么多能量才撞得出一对', en: 'Threshold: energy needed to make a pair' },
    bandEdge: { zh: '导带底 E_c、价带顶 E_v', en: 'Band edges E_c, E_v' },
    wall: { zh: '禁带之墙（宽 d）', en: 'Band-gap wall (width d)' },
    tunnel: { zh: '隧穿：同一能量横穿禁带', en: 'Tunnelling: across the gap at constant energy' },
    window: { zh: '隧穿窗口', en: 'Tunnelling window' },
    valence: { zh: '价带（填满电子）', en: 'Valence band (full)' },
    ef: { zh: '费米能级', en: 'Fermi level' },
    range: { zh: '手册温度系数范围', en: 'Datasheet TC range' },
    mid: { zh: '范围中值', en: 'Mid-range' },
    current: { zh: '电流（流动越快电流越大）', en: 'Current (faster = larger)' },
    loop: { zh: '正反馈环（越粗越强）', en: 'Positive feedback (thicker = stronger)' },
  },
  scaled: {
    intro: {
      zh: '突变结、耗尽层近似估算；掺杂浓度按击穿电压反推（手册不给），离子个数只是示意。三款器件横轴比例相同。',
      en: 'Abrupt junction, depletion approximation; doping is inferred from the breakdown voltage (not in datasheets); ion counts are illustrative. Same x scale for all three devices.',
    },
    avalanche: {
      zh: '示意：时间大大放慢；平均自由程画成 U_Z 下耗尽层宽度的 1/16（真实只有十纳米量级）；座位间距不按原子间距。按"幸运电子"模型：每次碰撞后从静止重新加速，一次自由飞行攒够能量就撞出一对。舞台的平均自由程放大了，所以撞出阈值不取真实值，而按模型的倍增因子 M 标定，多次平均与 M 一致；M 超过 20 时画面按 20 封顶。温度只改变平均自由程和 U_Z（按手册温度系数中值）；漏电流 I₀ 固定取 25 °C 的值，真实器件的 I₀ 随温度升高增长很快，所以改温度时不显示电流。',
      en: 'Illustrative: time is greatly slowed; the mean free path is drawn as 1/16 of the depletion width at U_Z (really of order 10 nm); seats are not drawn at the atomic spacing. "Lucky electron" model: after each collision a carrier restarts from rest, and if it gains enough energy in one free flight it makes a pair. Because the mean free path is enlarged, the threshold is not the real one but is calibrated so that the average equals the model multiplication M; M is capped at 20 on screen. Temperature changes only the mean free path and U_Z (mid datasheet TC); the leakage I₀ is held at its 25 °C value, whereas in a real part it rises fast with temperature, so the current is hidden when you change the temperature.',
    },
    zener: {
      zh: '座位视角：墙宽取隧穿窗口中部能量处的水平距离 d，座位间距不按原子间距。能带视角：突变结、耗尽层近似，不计重掺杂下的简并与禁带变窄。两种画面的隧穿速率都按电流比例示意；真实电子在禁带中没有确定的轨迹。',
      en: 'Seats view: the wall width is the horizontal distance d at mid-window energy; seats are not drawn at the atomic spacing. Band view: abrupt junction, depletion approximation; degeneracy and band-gap narrowing are ignored. In both, the tunnelling rate follows the current; a real electron has no defined path inside the gap.',
    },
    compare: {
      zh: '只画三款器件的手册数据；4E_g/q、6E_g/q 是 Sze 的经验分界，不是硬界线。W、𝓔max 为突变结在 U_Z、25 °C 时的估算。',
      en: 'Datasheet values of three devices only; 4E_g/q and 6E_g/q are Sze’s rules of thumb, not hard limits. W and 𝓔max are abrupt-junction estimates at U_Z, 25 °C.',
    },
    thermal: {
      zh: '单阶热模型 C_th·dT_j/dt = P − (T_j − T_a)/R_θ，热时间常数取 3 s（示意，真实器件从几秒到几十秒）；散热差的 350 °C/W 为示意值。只计 U_Z 的温度系数，漏电流与串联电阻不随温度变。T_j 超过 175 °C 视为损坏，模型到此为止。',
      en: 'Single-pole thermal model C_th·dT_j/dt = P − (T_j − T_a)/R_θ with a 3 s time constant (illustrative; real parts take seconds to tens of seconds); 350 °C/W for poor cooling is illustrative. Only the U_Z temperature coefficient is modelled. Above 175 °C the part counts as destroyed and the model stops.',
    },
  },
  /** 画布上的文字 */
  canvas: {
    scr: { zh: '耗尽层 {w}', en: 'Depletion {w}' },
    eAxis: { zh: '电场 𝓔（MV/cm）', en: 'Field 𝓔 (MV/cm)' },
    xAxis: { zh: '位置 x（冶金结为原点）', en: 'Position x (junction at 0)' },
    atVZ: { zh: '时', en: '' },
    zoom: { zh: '放大约 {k} 倍', en: '≈{k}× zoom' },
    field: { zh: '电场', en: 'Field' },
    fieldDir: { zh: '电场方向 N → P', en: 'Field points N → P' },
    inject: { zh: '少子电子从 P⁺ 侧进入耗尽层（漏电流的来源）', en: 'Minority electrons enter from the P⁺ side (the leakage current)' },
    Ec: { zh: 'E_c', en: 'E_c' },
    Ev: { zh: 'E_v', en: 'E_v' },
    EF: { zh: 'E_F', en: 'E_F' },
    window: { zh: '隧穿窗口', en: 'Tunnelling window' },
    tunnelD: { zh: 'd ≈ {d} nm', en: 'd ≈ {d} nm' },
    qV: { zh: 'qU_j = {v} eV', en: 'qU_j = {v} eV' },
    eg25: { zh: '虚线：25 °C 的 E_v', en: 'Dashed: E_v at 25 °C' },
    energy: { zh: '电子能量', en: 'Electron energy' },
    tcAxis: { zh: '温度系数（%/°C）', en: 'Temperature coefficient (%/°C)' },
    vzAxis: { zh: '稳压值 U_Z（V，对数坐标）', en: 'U_Z (V, log scale)' },
    tunnelZone: { zh: '隧穿为主', en: 'Tunnelling' },
    mixedZone: { zh: '两者并存', en: 'Both' },
    avZone: { zh: '雪崩为主', en: 'Avalanche' },
    colDev: { zh: '型号', en: 'Part' },
    colVZ: { zh: 'U_Z', en: 'U_Z' },
    colMech: { zh: '机理', en: 'Mechanism' },
    colTC: { zh: '温度系数 %/°C', en: 'TC %/°C' },
    mechT: { zh: '齐纳（隧穿）', en: 'Zener (tunnel)' },
    mechM: { zh: '两者并存', en: 'Mixed' },
    mechA: { zh: '雪崩', en: 'Avalanche' },
    src: { zh: 'U_S = {v} V', en: 'U_S = {v} V' },
    rLim: { zh: 'R_lim = {r} Ω', en: 'R_lim = {r} Ω' },
    wire: { zh: '不限流：只有电源内阻与导线 {r} Ω', en: 'No limit: only {r} Ω of source and wiring' },
    loopP: { zh: '功耗 P ↑', en: 'Power P ↑' },
    loopT: { zh: '结温 T_j ↑', en: 'T_j ↑' },
    loopV: { zh: 'U_Z ↓（负温度系数）', en: 'U_Z ↓ (negative TC)' },
    loopI: { zh: '电流 I ↑', en: 'Current I ↑' },
    gain: { zh: '环路增益 G = {g}', en: 'Loop gain G = {g}' },
    tjMax: { zh: 'T_j,max 175 °C', en: 'T_j,max 175 °C' },
    steady: { zh: '稳态 {t} °C', en: 'Steady state {t} °C' },
    steadyOff: { zh: '没有稳态：持续升温', en: 'No steady state: keeps heating' },
    noFb: { zh: '（若 U_Z 不随温度变：{t} °C）', en: '(if U_Z did not change: {t} °C)' },
    brake: { zh: 'R_lim 让电流几乎不随 U_Z 变，反馈很弱', en: 'R_lim keeps the current nearly fixed; the feedback is weak' },
    lastTree: { zh: '这一次：进 1 个电子 → 出 {n} 个', en: 'This time: 1 electron in → {n} out' },
    nearMiss: { zh: '差一点！能量不够，只变成了热', en: 'So close! Not enough energy: just heat' },
    waitNext: { zh: '这一棵长完了，马上注入下一个电子', en: 'This tree is done; the next electron is on its way' },
    thrE: { zh: '电子的撞出线：攒到这么多能量才撞得出一对（≈ 1.5E_g，示意）', en: 'Electron threshold: energy needed to make a pair (≈ 1.5E_g, schematic)' },
    thrH: { zh: '空穴的撞出线（硅里空穴更难撞出一对）', en: 'Hole threshold (holes ionise less readily in Si)' },
    bandNote: { zh: '纵向示意：禁带画宽、电势差压缩，未按比例。电子离导带底越高，攒到的能量越多；空穴向下同理', en: 'Not to scale vertically: the gap is widened and the potential drop squeezed. The higher an electron sits above E_c, the more energy it has gained (holes: downwards)' },
    wall: { zh: '禁带之墙 d ≈ {d} nm', en: 'Band-gap wall d ≈ {d} nm' },
    wallNote: { zh: '反压越高，墙越薄，穿过去的越多', en: 'More reverse voltage → thinner wall → more crossings' },
    closed: { zh: '反压还不够：P 区价带还没高过 N 区导带，没有可以穿过去的地方', en: 'Not enough reverse voltage yet: the P valence band is not above the N conduction band' },
    noAccel: { zh: '不用加速，也不碰撞：一步穿过去，不会一传二', en: 'No acceleration, no collisions: one step across, no chain reaction' },
    scaleCmp: { zh: '对比：1N4757A（雪崩）的耗尽层约 {w}，是这里的 {k} 倍', en: 'For comparison, the 1N4757A (avalanche) depletion layer is about {w}, {k}× wider' },
    trace: { zh: '结温 T_j（°C）', en: 'Junction temp. T_j (°C)' },
    tAxis: { zh: '时间（s，舞台时间）', en: 'Time (s, stage time)' },
    burnt: { zh: 'T_j 超过 175 °C：视为损坏（热击穿）', en: 'T_j above 175 °C: destroyed (thermal breakdown)' },
  },
  chart: {
    title: { zh: '稳压二极管的 V-A 特性', en: 'Zener diode V-A curve' },
    hint: { zh: '反向段两种比例：−6 V 以内放大', en: 'Two scales on the reverse side: expanded within −6 V' },
    hintCompare: { zh: '电流按各自 I_ZT 归一化', en: 'Current normalised to each I_ZT' },
    hintThermal: { zh: '工作点 = 器件曲线 ∩ 负载线', en: 'Operating point = device curve ∩ load line' },
    inset: { zh: '击穿区放大', en: 'Breakdown knee' },
    now: { zh: '当前温度', en: 'At this temperature' },
    nowTj: { zh: '当前结温', en: 'At this T_j' },
    ghost: { zh: '25 °C', en: '25 °C' },
    load: { zh: '负载线 I = (U_S − V)/R', en: 'Load line I = (U_S − V)/R' },
    pmax: { zh: '允许功耗 (T_j,max − T_a)/R_θ = {p} W', en: 'Allowed power (T_j,max − T_a)/R_θ = {p} W' },
    op: { zh: '工作点', en: 'Operating point' },
    leak: { zh: '反向漏电流只有 µA 级，线性坐标上贴着零线', en: 'Reverse leakage is only µA: it hugs zero on a linear axis' },
  },
}
